Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2021-04, with the labels that each got.

#74 charts: modify the keyword #75
  charts/Chart.yaml
  charts/README.md
  charts/templates/_helpers.tpl
  charts/templates/configmap.yaml
  charts/templates/rbac.yaml
  charts/templates/secrets.yaml
  charts/templates/service.yaml
  charts/templates/serviceaccount.yaml
  charts/templates/servicemonitor.yaml
  charts/templates/statefulset.yaml
  charts/values.yaml
  docs/zh-cn/charts.md
Labels: documentation, enhancement

#88 *. : Modify README.md and README_zh.md #75
  README.md
  README_zh.md
Labels: documentation

#91 .github: add pull request and issue templates #90
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-question.md
  .github/ISSUE_TEMPLATE/support-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#93 .github: fix the error file name #90
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug

#96 README.md: fix some errors adjust some descriptions #37
  README.md
  README_zh.md
Labels: documentation, enhancement
