Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2021-11, with the labels that each got.

#280 Makefile: Synchronize the generated files to Chart while generating CRD.
  Makefile
Labels: enhancement

#286 status: Nodes.Conitions only contains the conition of the node present in the cluster. #283
  mysqlcluster/syncer/status.go
Labels: bug

#217 Feature fix bug of not effective version of mysql56 #203
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
  mysqlcluster/syncer/metrics_service.go
  sidecar/config.go
  utils/constants.go
Labels: bug, enhancement

#295 *: Initialize operator chart repo.
  index.yaml
  mysql-operator-0.1.1.tgz
Labels: enhancement

#285 *: Support display the raft status of the node in nodes.conditions. #284
  api/v1alpha1/mysqlcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  cmd/manager/main.go
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  controllers/mysqlcluster_controller.go
  controllers/mysqluser_controller.go
  controllers/status_controller.go
  internal/http_executor.go
  internal/pod_executor.go
  internal/xenon_executor.go
  internal/xenon_request.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/status.go
  utils/common.go
  utils/constants.go
Labels: enhancement

#296 Dockerfile: Provide backup of district/static:nonroot image. #287
  Dockerfile
Labels: enhancement

#299 *: update helm repo.
  index.yaml
  mysql-operator-0.1.0.tgz
  mysql-operator-0.1.1.tgz
Labels: chart

#301 charts: Support to modify the RBAC image of Operator. #300
  charts/mysql-operator/templates/deployment.yaml
  charts/mysql-operator/values.yaml
Labels: enhancement, chart

#298 *: Update deployment document and outdated description.
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/Chart.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
Labels: documentation, enhancement, chart

#294 workflow: Manage Chart using Helm REPO. #290
  .github/workflows/code_check.yml
  .github/workflows/publish_charts.yml
Labels: enhancement, P2, workflow

#293 sidecar: change restore.sh to go codes #292
  sidecar/config.go
  sidecar/init.go
Labels: enhancement

#282 *：update replicas without restart
  api/v1alpha1/mysqlcluster_types.go
  internal/xenon_executor.go
  mysqlcluster/container/backup.go
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/syncer/status.go
  sidecar/config.go
  sidecar/init.go
  utils/common.go
  utils/constants.go
Labels: enhancement

#308 mysqlcluster: support replica is 0, but data need to be reserverd #304
  mysqlcluster/syncer/statefulset.go
Labels: enhancement

#291 mysqlcluster,sidecar: support Clone initial when add new pod, and fix bug after extend pvc, restore from backup fail #250, #370
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/syncer/follower_service.go
  mysqlcluster/syncer/headless_service.go
  mysqlcluster/syncer/leader_service.go
  sidecar/config.go
  sidecar/init.go
  sidecar/server.go
  sidecar/util.go
Labels: enhancement
