Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2021-12, with the labels that each got.

#314 syncer: Set the health label to `no` before updating pod. #310
  mysqlcluster/syncer/statefulset.go
Labels: bug

#315 syncer: remove preUpdate logic. #312
  mysqlcluster/syncer/statefulset.go
Labels: bug

#318 sysbench press the database, Pod is recreated by k8s #305
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
Labels: bug

#321 syncer: Optimize update POD trigger conditions
  mysqlcluster/syncer/statefulset.go
Labels: bug

#328 sidecar: first choose follower to clone init #322
  sidecar/init.go
Labels: enhancement

#333 docs,hack: support manual repair the Invalid Pod #331
  docs/rebuild.md
  hack/rebuild.sh
Labels: enhancement

#342 charts: change the default path of the rbac proxy image. #146
  charts/mysql-operator/values.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: duplicate

#339 docs/rancher *: Add docs about deploy radondb mysql on rancher #338
  README.md
  README_zh.md
  docs/rancher/_images/helm_options.png
  docs/rancher/_images/import_yaml.png
  docs/rancher/_images/kubectl_command.png
  docs/rancher/_images/mysql_operator_chart.png
  docs/rancher/_images/mysql_operator_metadata.png
  docs/rancher/_images/mysql_operator_values.png
  docs/rancher/_images/pod_running.png
  docs/rancher/deploy_radondb-mysql_operator_on_rancher.md
Labels: documentation

#334 *: Support more role labels.
  mysqlcluster/syncer/follower_service.go
  mysqlcluster/syncer/leader_service.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/status.go
  sidecar/config.go
  sidecar/init.go
  sidecar/util.go
Labels: enhancement

#347 e2e: e2e framework and simple test case.
  go.mod
  go.sum
  test/e2e/README.md
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/framework.go
  test/e2e/framework/ginkgowrapper/BUILD
  test/e2e/framework/ginkgowrapper/wrapper.go
  test/e2e/framework/helm.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/e2e/reporter.go
  test/e2e/simplecase/list_namespace.go
  test/e2e/staticcheck.conf
Labels: e2e
