Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2021-07, with the labels that each got.

#132 docs: quickstart for radondb mysql operator #127
  docs/Kubernetes/deploy_radondb-mysql_operator_on_k8s.md
Labels: documentation

#142 charts: Move the images and change the key word #140
  charts/helm/Chart.yaml
  charts/helm/README.md
  charts/helm/dockerfiles/mysql/README.md
  charts/helm/dockerfiles/xenon/README.md
  charts/helm/values.yaml
  docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
  docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_appstore.md
  docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_repo.md
  docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md
  docs/zh-cn/charts.md
  docs/zh-cn/mysql.md
  docs/zh-cn/xenon.md
Labels: documentation, enhancement

#141 utils: Fix possible misuse of reflect.SliceHeader vet error when go 1.16.6 #139
  utils/unsafe.go
  utils/unsafe_test.go
Labels: bug

#133 *: support roll update
  api/v1alpha1/cluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_clusters.yaml
  cluster/cluster.go
  cluster/container/init_mysql.go
  cluster/container/init_sidecar.go
  cluster/container/mysql.go
  cluster/syncer/secret.go
  cluster/syncer/statefulset.go
  cluster/syncer/status.go
  config/crd/bases/mysql.radondb.com_clusters.yaml
  config/samples/mysql_v1alpha1_cluster.yaml
  controllers/cluster_controller.go
  go.mod
  internal/sql_runner.go
  sidecar/config.go
  sidecar/init.go
  sidecar/util.go
  utils/common.go
  utils/constants.go
Labels: P0, enhancement
