Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2021-09, with the labels that each got.

#197 *: backup to S3 and restore from S3 #116
  .github/workflows/auto_build_operator.yml
  Dockerfile
  Dockerfile.sidecar
  PROJECT
  api/v1alpha1/backup_types.go
  api/v1alpha1/cluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  backup/backup.go
  backup/status.go
  backup/syncer/job.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_clusters.yaml
  charts/mysql-operator/templates/cluster_rbac.yaml
  charts/mysql-operator/values.yaml
  cluster/container/backup.go
  cluster/container/container.go
  cluster/container/init_sidecar.go
  cluster/container/init_sidecar_test.go
  cluster/syncer/metrics_service.go
  cluster/syncer/secret.go
  cluster/syncer/statefulset.go
  cmd/manager/main.go
  cmd/sidecar/main.go
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_clusters.yaml
  config/crd/kustomization.yaml
  config/rbac/backup_editor_role.yaml
  config/rbac/backup_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/backup_secret.yaml
  config/samples/mysql_v1alpha1_backup.yaml
  config/samples/mysql_v1alpha1_cluster.yaml
  controllers/backup_controller.go
  controllers/suite_test.go
  docs/deploy_backup_restore_s3.md
  sidecar/config.go
  sidecar/init.go
  sidecar/server.go
  sidecar/takebackup.go
  sidecar/util.go
  utils/common.go
  utils/constants.go
Labels: enhancement

#213 *: format the code with gofumpt #212
  api/v1alpha1/cluster_types.go
  cluster/cluster_test.go
  cluster/container/backup.go
  cluster/container/init_mysql_test.go
  cluster/container/init_sidecar.go
  cluster/container/init_sidecar_test.go
  cluster/container/mysql_test.go
  cluster/syncer/metrics_service.go
  cluster/syncer/secret.go
  cluster/syncer/statefulset.go
  internal/sql_runner.go
  sidecar/config.go
  utils/common.go
  utils/constants.go
Labels: format

#205 *.: fix default mysql version 5.7.33 to 5.7.34
  cluster/cluster_test.go
  cluster/container/init_mysql_test.go
  cluster/container/init_sidecar_test.go
  cluster/container/mysql_test.go
  utils/constants.go
Labels: enhancement

#202 docs *: Add files about monitoring #169
  README.md
  README_zh.md
  docs/KubeSphere/png/主节点端口.png
  docs/KubeSphere/png/从节点端口.png
  docs/KubeSphere/png/企业空间.png
  docs/KubeSphere/png/应用管理.png
  docs/KubeSphere/png/应用负载.png
  docs/KubeSphere/png/控制台部署成功.png
  docs/KubeSphere/png/访问方式.png
  docs/KubeSphere/png/连接客户端节点.png
  docs/KubeSphere/png/项目管理.png
  docs/_images/config_dashboard.png
  docs/_images/monitor_overview.png
  docs/_images/monitor_service.png
  docs/_images/mysql_exporter.png
  docs/_images/pod_metrics.png
  docs/_images/prometheus_grafana.png
  docs/deploy_monitoring.md
  docs/images/vx_code_1280.jpg
  docs/images/vx_code_258.jpg
  docs/images/vx_code_430.jpg
  docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
  docs/kubesphere/_images/application.png
  docs/kubesphere/_images/appstore.png
  docs/kubesphere/_images/appstore_radondb_mysql.png
  docs/kubesphere/_images/config_vnet.png
  docs/kubesphere/_images/deploy_confirm.png
  docs/kubesphere/_images/deploy_radondb_mysql.png
  docs/kubesphere/_images/deploy_success.png
  docs/kubesphere/_images/loadbalancer.png
  docs/kubesphere/_images/loadbalancer_port.png
  docs/kubesphere/_images/node_port.png
  docs/kubesphere/_images/nodeport.png
  docs/kubesphere/_images/running.png
  docs/kubesphere/_images/service.png
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere.md
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere_appstore.md
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere_repo.md
Labels: documentation

#206 api,cluster,sidecar: fix the bug for infinite loop #201, #219
  api/v1alpha1/backup_types.go
  cluster/syncer/statefulset.go
  sidecar/config.go
Labels: bug

#227 *: simplify backup code #226
  api/v1alpha1/cluster_types.go
  backup/syncer/job.go
  charts/helm/templates/secrets.yaml
  charts/helm/values.yaml
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_clusters.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_clusters.yaml
  config/samples/mysql_v1alpha1_cluster.yaml
  controllers/backup_controller.go
  utils/constants.go
Labels: enhancement

#233 docs *：Modify the default name and password #191
  docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere.md
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere_appstore.md
  docs/kubesphere/deploy_radondb-mysql_on_kubesphere_repo.md
Labels: documentation

#230 *: Optimize the logic of creating sqlrunner. #229
  cluster/cluster.go
  cluster/syncer/statefulset.go
  cluster/syncer/status.go
  cmd/manager/main.go
  controllers/cluster_controller.go
  controllers/status_controller.go
  internal/query.go
  internal/sql_runner.go
  utils/constants.go
Labels: enhancement

#241 *: Remove the helm version deployment document link and fix operator deployment document.
  README.md
  README_zh.md
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
Labels: documentation

#239 controller: fix the 8 backupJob but create 11 copies #237
  controllers/backup_controller.go
Labels: bug

#231 test: e2e prototype framework stage 1 #199
  Makefile
  go.mod
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/test_context.go
Labels: test
