Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-10, with the labels that each got.

#711 mysqlcluster: mysqlopt replace init config should ignore bar or unde…
  mysqlcluster/syncer/mysql_cm.go
Labels: bug

#583 README: update architecture
  docs/images/radondb-mysql_Architecture.png
  docs/images/radondb-mysql_Architecture_1.png
Labels: documentation

#686 feat(e2e): support sysbench
  test/e2e/framework/sysbench.go
  test/e2e/install/cleanup.go
  test/e2e/install/cluster.go
  test/e2e/install/cluster_asset.go
Labels: e2e

#713 mysqlcluster: fix failed to start pod for first time #545
  mysqlcluster/container/auditlog.go
  mysqlcluster/container/auditlog_test.go
  mysqlcluster/container/slowlog.go
  mysqlcluster/container/slowlog_test.go
Labels: bug

#717 *: support the x.x.x.x:/dbbackup nfs address. #716
  api/v1alpha1/mysqlcluster_webhook.go
  backup/syncer/job.go
  config/samples/nfs_server.yaml
  mysqlcluster/mysqlcluster.go
  utils/common.go
Labels: enhancement
