Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-11, with the labels that each got.

#719 container: support image namespace override
  Makefile
  backup/syncer/job.go
  charts/mysql-operator/Chart.yaml
  charts/mysql-operator/templates/deployment.yaml
  charts/mysql-operator/values.yaml
  controllers/backup_controller.go
  controllers/status_controller.go
  mysqlcluster/container/auditlog_test.go
  mysqlcluster/container/container.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/metrics_test.go
  mysqlcluster/container/slowlog_test.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
Labels: chart

#723 chart: radondb-mysql80-template cannot use mysql5 config #720
  charts/mysql-operator/templates/mysql80_template.yaml
Labels: bug

#724 api: add mysqltemplate webhook check #722
  api/v1alpha1/mysqlcluster_webhook.go
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
Labels: bug

#731 api: Add webhook check for sidecar image
  api/v1alpha1/mysqlcluster_webhook.go
Labels: enhancement

#729 *: replace expr commond to bc #725
  Dockerfile.sidecar
  backup/syncer/job.go
Labels: bug

#721 *: Support make S3 and NFS backup schedule together #689
  api/v1alpha1/mysqlcluster_types.go
  api/v1alpha1/mysqlcluster_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  backup/cronbackup.go
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  controllers/backupcron_controller.go
Labels: enhancement

#734 mysqlcluster: Fix image namespace override
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
Labels: bug

#736 doc,chart: add the both s3 nfs backup documents #735
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  docs/en-us/backup_cron.md
  docs/zh-cn/backup_cron.md
Labels: documentation

#738 controllers: fix the bug for auto backup #737
  controllers/backupcron_controller.go
Labels: bug

#741 controller: fix the auto backup nfs error #740
  controllers/backupcron_controller.go
Labels: bug

#742 *: update version to 2.3.0
  Makefile
  api/v1alpha1/backup_types.go
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/Chart.yaml
  charts/mysql-operator/charts/mysql-cluster/Chart.yaml
  charts/mysql-operator/charts/mysql-cluster/values.yaml
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  charts/mysql-operator/values.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/manager/kustomization.yaml
  config/samples/mysql_v1alpha1_backup.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
  test/e2e/framework/mysqlcluster.go
  test/e2e/framework/test_context.go
Labels: chart
