Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-02, with the labels that each got.

#376 docs *: Adjust the file directory and add new deployment files #152
  README.md
  README_zh.md
  docs/en-us/_images/certify_url.png
  docs/en-us/_images/kubectl_terminal.png
  docs/en-us/_images/operator_yaml.png
  docs/en-us/_images/pod_terminal.png
  docs/en-us/deploy_backup_restore_s3.md
  docs/en-us/deploy_radondb-mysql_operator_on_kubesphere.md
  docs/en-us/rebuild.md
  docs/en-us/setup-rw-svc.md
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
  docs/zh-cn/_images/certify_url.png
  docs/zh-cn/_images/config_dashboard.png
  docs/zh-cn/_images/helm_options.png
  docs/zh-cn/_images/import_yaml.png
  docs/zh-cn/_images/kubectl_command.png
  docs/zh-cn/_images/kubectl_terminal.png
  docs/zh-cn/_images/monitor_overview.png
  docs/zh-cn/_images/monitor_service.png
  docs/zh-cn/_images/mysql_exporter.png
  docs/zh-cn/_images/mysql_operator_chart.png
  docs/zh-cn/_images/mysql_operator_metadata.png
  docs/zh-cn/_images/mysql_operator_values.png
  docs/zh-cn/_images/operator_yaml.png
  docs/zh-cn/_images/pod_metrics.png
  docs/zh-cn/_images/pod_running.png
  docs/zh-cn/_images/pod_terminal.png
  docs/zh-cn/_images/prometheus_grafana.png
  docs/zh-cn/config_para.md
  docs/zh-cn/deploy_backup_restore_s3.md
  docs/zh-cn/deploy_monitoring.md
  docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md
  docs/zh-cn/deploy_radondb-mysql_operator_on_kubesphere.md
  docs/zh-cn/deploy_radondb-mysql_operator_on_rancher.md
  docs/zh-cn/mgt_mysqluser.md
  docs/zh-cn/rebuild.md
  docs/zh-cn/setup-rw-svc.md
  docs/zh-cn/version1.0/_images/application.png
  docs/zh-cn/version1.0/_images/appstore.png
  docs/zh-cn/version1.0/_images/appstore_radondb_mysql.png
  docs/zh-cn/version1.0/_images/config_vnet.png
  docs/zh-cn/version1.0/_images/deploy_confirm.png
  docs/zh-cn/version1.0/_images/deploy_radondb_mysql.png
  docs/zh-cn/version1.0/_images/deploy_success.png
  docs/zh-cn/version1.0/_images/loadbalancer.png
  docs/zh-cn/version1.0/_images/loadbalancer_port.png
  docs/zh-cn/version1.0/_images/node_port.png
  docs/zh-cn/version1.0/_images/nodeport.png
  docs/zh-cn/version1.0/_images/running.png
  docs/zh-cn/version1.0/_images/service.png
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubernetes.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere_appstore.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere_repo.md
Labels: documentation

#360 e2e: Upgrade Ginkgo to V2 version.
  controllers/suite_test.go
  go.mod
  go.sum
  test/e2e/README.md
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/ginkgowrapper/wrapper.go
  test/e2e/framework/helm.go
  test/e2e/framework/reporter.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/e2e/reporter.go
  test/e2e/simplecase/list_namespace.go
Labels: enhancement, e2e

#381 *: fix .gitignore about e2e logs and function
  .gitignore
  test/e2e/simplecase/list_namespace.go
Labels: format, e2e

#380 *: Support custom repository address of images. #378
  backup/syncer/job.go
  charts/mysql-operator/templates/deployment.yaml
  charts/mysql-operator/values.yaml
  mysqlcluster/container/auditlog_test.go
  mysqlcluster/container/container.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/metrics_test.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/slowlog_test.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
Labels: enhancement

#384 Add operator version v2.1.2 to helm repo.
  .gitignore
  index.yaml
  mysql-operator-0.1.1.tgz
Labels: chart

#394 syncer: Uniform use of global variables set role labels.
  mysqlcluster/syncer/statefulset.go
Labels: enhancement
