Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-03, with the labels that each got.

#392 hack: Change Xenon's Dockerfile image branch to master. #336
  hack/xenon/Dockerfile
Labels: enhancement

#383 mysqlcluster: Debug Mode for Pod #375
  docs/en-us/DebugMode.md
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
Labels: enhancement

#402 docs：Add a description of `service_name` connection method #401
  docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md
  docs/zh-cn/deploy_radondb-mysql_operator_on_rancher.md
Labels: documentation

#405 container: Add xenoncli check in the liveness probe.
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
Labels: bug

#399 docs: Add offline deployment document. #396
  docs/zh-cn/deploy_radondb-mysql_operator_on_k8s_offline.md
Labels: documentation

#393 config: Add podAntiAffinity to default sample yaml. #371
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
Labels: documentation, enhancement

#389 mysqlcluster: Support automatic rebuild of nodes by label.
  docs/en-us/rebuild.md
  mysqlcluster/syncer/status.go
  utils/constants.go
Labels: enhancement

#418 status: Skip the unavailable node and set default node status. #417
  mysqlcluster/syncer/status.go
  utils/constants.go
Labels: bug, P0

#419 chart: update chart version to v2.1.3.
  charts/mysql-operator/Chart.yaml
Labels: chart

#411 cmd: Change HttpServer stop channel to buffered channel. #411
  cmd/sidecar/main.go
Labels: bug

#422 workflow: Publish release only one click. #421
  .github/release-drafter.yml
  .github/workflows/build_operator_image.yml
  .github/workflows/build_sidecar_image.yml
  .github/workflows/code_check.yml
  .github/workflows/greetings.yml
  .github/workflows/publish_charts.yml
  .github/workflows/publish_images.yml
  .github/workflows/publish_release.yml
  .github/workflows/release_drafter.yml
  .github/workflows/unit_tests.yml
Labels: enhancement, workflow

#413 *: Save Xenon's metadata to persistent storage. #406
  mysqlcluster/container/backup.go
  mysqlcluster/container/init_mysql.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  sidecar/init.go
  sidecar/util.go
  utils/constants.go
Labels: enhancement

#430 docs: Translate 'deploy_radondb-mysql_operator_on_k8s.md' and 'deploy_radondb-mysql_operator_on_rancher.md'
  docs/en-us/deploy_radondb-mysql_operator_on_k8s.md
  docs/en-us/deploy_radondb-mysql_operator_on_rancher.md
Labels: documentation

#432 workflow: Specify version of staticcheck. #431
  .github/workflows/code_check.yml
Labels: bug, workflow
