Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-06, with the labels that each got.

#509 syncer: Reduce useless log output #508
  controllers/mysqlcluster_controller.go
  controllers/status_controller.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/status.go
Labels: format

#512 syncer: failed to patch pod labels.
  mysqlcluster/syncer/status.go
Labels: bug

#386 *: support the cronjob to backup #215
  PROJECT
  api/v1alpha1/mysqlcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  backup/cronbackup.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  cmd/manager/main.go
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
  controllers/backupcron_controller.go
  docs/en-us/backupSchedule.md
  go.mod
  go.sum
Labels: enhancement

#513 chart: Operator mount the host's time zone. #511
  charts/mysql-operator/templates/deployment.yaml
Labels: bug, chart

#505 docs: Update and translate documentation. #496
  docs/en-us/deploy_backup_restore_nfs.md
  docs/en-us/setup-rw-svc.md
  docs/zh-cn/DebugMode.md
  docs/zh-cn/build_images_and_apply.md
  docs/zh-cn/charts.md
  docs/zh-cn/deploy_backup_restore_nfs.md
  docs/zh-cn/deploy_backup_restore_s3.md
  docs/zh-cn/deploy_radondb-mysql_operator_on_k8s_offline.md
  docs/zh-cn/rebuild.md
  docs/zh-cn/setup-rw-svc.md
  docs/zh-cn/version1.0/_images/application.png
  docs/zh-cn/version1.0/_images/appstore.png
  docs/zh-cn/version1.0/_images/appstore_radondb_mysql.png
  docs/zh-cn/version1.0/_images/config_vnet.png
  docs/zh-cn/version1.0/_images/deploy_confirm.png
  docs/zh-cn/version1.0/_images/deploy_radondb_mysql.png
  docs/zh-cn/version1.0/_images/deploy_success.png
  docs/zh-cn/version1.0/_images/loadbalancer.png
  docs/zh-cn/version1.0/_images/loadbalancer_port.png
  docs/zh-cn/version1.0/_images/node_port.png
  docs/zh-cn/version1.0/_images/nodeport.png
  docs/zh-cn/version1.0/_images/running.png
  docs/zh-cn/version1.0/_images/service.png
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubernetes.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere_appstore.md
  docs/zh-cn/version1.0/deploy_radondb-mysql_on_kubesphere_repo.md
Labels: documentation

#465 controller: operator crash #464
  controllers/mysqlcluster_controller.go
Labels: bug

#518 *: Support tls for external #492
  .gitignore
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  docs/zh-cn/how_to_use_tls.md
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/mysql.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/syncer/mysql_cm.go
  mysqlcluster/syncer/mysql_configs.go
  sidecar/init.go
  utils/constants.go
Labels: enhancement

#526 syncer: Support update the mysql plugin configuration.
  mysqlcluster/syncer/mysql_cm.go
Labels: bug, enhancement

#510 mysqlcluster: innodb_log_file_size auto config. #501
  mysqlcluster/mysqlcluster.go
  mysqlcluster/syncer/mysql_configs.go
Labels: enhancement

#503 syncer: Optimize the logic of updating pod.
  mysqlcluster/syncer/statefulset.go
Labels: bug, Improvement

#530 fix(syncer): failed to update my.cnf
  mysqlcluster/syncer/mysql_cm.go
Labels: duplicate

#536 mysqlcluster: fix the error for pod's label no change #534
  mysqlcluster/syncer/status.go
Labels: bug

#535 fix(cluster): Rolling update trigger logic incorrect.
  mysqlcluster/syncer/statefulset.go
Labels: bug

#549 container: adjust readiness timeout #542
  mysqlcluster/container/backup.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
Labels: Improvement

#556 api: Disable TOKUDB by default.
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
Labels: duplicate, enhancement

#554 sidecar:prevent useless clone data when booting sidecar
  sidecar/init.go
Labels: enhancement

#539 fix(cluster): add a check for the unfinished update
  internal/sql_runner.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/status.go
Labels: bug, duplicate

#560 controllers: when name over 63, write error message in backup status …
  controllers/backup_controller.go
Labels: bug

#563 mysqlcluster: fix the bug for replace config items #562
  mysqlcluster/syncer/mysql_cm.go
Labels: bug
