Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-01, with the labels that each got.

#354 *: Make the versions provided by helm repo and release consistent. #352
  index.yaml
  mysql-operator-0.1.1.tgz
Labels: chart

#362 doc: Download the latest stable version of YAML from Release.
  docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
Labels: documentation

#366 internal: Fixed the cluster status cannot be changed after the POD ex…
  internal/http_executor.go
Labels: bug

#370 sidecar: sacle 2 to 3 ,mysql-operator restart #368
  sidecar/config.go
Labels: bug
