Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-04, with the labels that each got.

#410 docs: Add tutorial of building images. #409
  docs/en-us/build_images_and_apply.md
Labels: documentation, require-doc

#416 Chart: optimize operator availability
  charts/mysql-operator/templates/deployment.yaml
  charts/mysql-operator/values.yaml
Labels: enhancement, chart

#434 mysqlcluser: headless svc has other cluster pods #433
  mysqlcluster/syncer/headless_service.go
Labels: bug

#435 cluster,config,sidecar,utils: support the MySQL8.0 #176
  Makefile
  config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
  docs/en-us/deploy_radondb_mysql8.md
  mysqlcluster/container/init_mysql.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
  mysqlcluster/syncer/config_map.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/variables.go
  sidecar/config.go
  sidecar/init.go
  utils/constants.go
Labels: enhancement

#437 *: Optimize mysql8 related logic.
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  charts/mysql-operator/values.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
  mysqlcluster/syncer/config_map.go
  mysqlcluster/syncer/mysql_configs.go
  sidecar/init.go
  utils/constants.go
Labels: enhancement, format

#443 Merge pull request #437 from runkecheng/feature_mysql8
  api/v1alpha1/backup_types.go
  api/v1alpha1/mysqlcluster_types.go
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  mysqlcluster/syncer/config_map.go
  mysqlcluster/syncer/mysql_configs.go
  sidecar/init.go
  utils/constants.go
Labels: format

#447 *: Save Xenon's metadata to config map.
  controllers/mysqlcluster_controller.go
  mysqlcluster/container/backup.go
  mysqlcluster/container/init_mysql.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
  mysqlcluster/syncer/mysql_cm.go
  mysqlcluster/syncer/xenon_cm.go
  sidecar/config.go
  sidecar/init.go
  sidecar/util.go
  utils/constants.go
Labels: duplicate, enhancement, test

#449 sidecar: Skip `reset slave all` when initialization.
  sidecar/config.go
  sidecar/init.go
Labels: bug

#452 workflow: support mysql8.0.
  .github/workflows/build_sidecar_image.yml
  .github/workflows/release_drafter.yml
Labels: duplicate, enhancement

#232 *: support backup/restore with NFS #148
  api/v1alpha1/backup_types.go
  api/v1alpha1/mysqlcluster_types.go
  backup/backup.go
  backup/syncer/job.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/backup_secret.yaml
  config/samples/mysql_v1alpha1_backup.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/nfs_rc.yaml
  config/samples/nfs_server.yaml
  config/samples/pv-claim.yml
  config/samples/pv-volume.yaml
  docs/deploy_backup_restore_nfs.md
  docs/en-us/deploy_backup_restore_s3.md
  mysqlcluster/container/backup.go
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/syncer/follower_service.go
  mysqlcluster/syncer/leader_service.go
  sidecar/config.go
  sidecar/init.go
  sidecar/server.go
  sidecar/takebackup.go
  utils/common.go
  utils/constants.go
Labels: enhancement

#456 config: fix bug about apiVersion #148
  config/samples/backup_secret.yaml
Labels: bug

#454 *：Simplify the use of NFS backup.
  api/v1alpha1/backup_types.go
  api/v1alpha1/mysqlcluster_types.go
  backup/syncer/job.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/mysql_v1alpha1_backup.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/nfs_pv.yaml
  config/samples/nfs_rc.yaml
  config/samples/nfs_server.yaml
  config/samples/pv-claim.yml
  docs/deploy_backup_restore_nfs.md
  docs/en-us/deploy_backup_restore_nfs.md
  docs/en-us/deploy_backup_restore_s3.md
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/mysqlcluster.go
Labels: documentation, duplicate, enhancement, CRD, require-doc

#455 chart: support NFS backup.
  charts/mysql-operator/templates/nfs_backup.yaml
  charts/mysql-operator/values.yaml
Labels: enhancement, chart, require-doc

#459 ci: Support custom release version.
  .github/workflows/publish_release.yml
  .github/workflows/release_drafter.yml
Labels: workflow, Improvement

#461 ci: Fix `build-arg` not take effect.
  .github/workflows/build_sidecar_image.yml
Labels: bug, workflow

#463 ci: fix syntax error in sidecar ci.
  .github/workflows/build_sidecar_image.yml
Labels: bug, workflow, Discovered by e2e

#468 Update Readme.md
  Readme.md
Labels: documentation

#471 Update README_zh.md.
  Readme.md
Labels: documentation

#473 mysqlcluster, sidecar: Support ipv6 address. #441
  sidecar/config.go
Labels: bug
