Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-08, with the labels that each got.

#466 e2e: cluster related api and test case. #344
  test/e2e/README.md
  test/e2e/cluster/cluster.go
  test/e2e/e2e_test.go
  test/e2e/framework/cluster_util.go
  test/e2e/framework/framework.go
  test/e2e/framework/helm.go
  test/e2e/framework/test_context.go
Labels: enhancement, e2e, require-doc

#643 backup,controller: add nfs crontab backup, and catch error when fail …
  backup/cronbackup.go
  backup/syncer/job.go
  controllers/backupcron_controller.go
Labels: bug

#610 doc: Add parameter introduction and connection tutorial
  docs/zh-cn/mgt_mysqluser.md
Labels: documentation, require-doc

#611 doc: translate manage_mysql_user and change file name. #564
  README_zh.md
  docs/en-us/manage_mysql_user.md
  docs/en-us/mgt_mysqlusser.md
  docs/zh-cn/manage_mysql_user.md
Labels: documentation

#662 controllers: fix the bug cronjob exits when cluster is gone #661
  backup/cronbackup.go
  controllers/backupcron_controller.go
Labels: bug

#665 controller: fix the bug missing label of recurrent #664
  controllers/backup_controller.go
Labels: bug

#519 chart: Support the use of Helm to install MySQL cluster
  charts/mysql-operator/charts/mysql-cluster/.helmignore
  charts/mysql-operator/charts/mysql-cluster/Chart.yaml
  charts/mysql-operator/charts/mysql-cluster/templates/NOTES.txt
  charts/mysql-operator/charts/mysql-cluster/templates/_helpers.tpl
  charts/mysql-operator/charts/mysql-cluster/templates/cert.tpl
  charts/mysql-operator/charts/mysql-cluster/templates/mysqlcluster.yaml
  charts/mysql-operator/charts/mysql-cluster/templates/mysqluser.yaml
  charts/mysql-operator/charts/mysql-cluster/templates/tls_secrets.yaml
  charts/mysql-operator/charts/mysql-cluster/values.yaml
  charts/mysql-operator/templates/NOTES.txt
  charts/mysql-operator/values.yaml
Labels: enhancement, chart

#658 *: rebuild from special pod #652
  config/samples/nfs_server.yaml
  mysqlcluster/syncer/role.go
  mysqlcluster/syncer/status.go
  sidecar/init.go
  utils/constants.go
Labels: bug

#677 *: update go version to 1.17
  .github/workflows/code_check.yml
  .github/workflows/unit_tests.yml
  Dockerfile
  Dockerfile.sidecar
  api/v1alpha1/zz_generated.deepcopy.go
  backup/syncer/job.go
  build/mysql/Dockerfile
  build/xenon/Dockerfile
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  controllers/backup_controller.go
  controllers/mysqlcluster_controller.go
  controllers/mysqluser_controller.go
  controllers/status_controller.go
  go.mod
  go.sum
  hack/xenon/Dockerfile
  mysqlcluster/container/backup.go
  mysqlcluster/container/container.go
  mysqlcluster/container/metrics.go
  mysqlcluster/container/metrics_test.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/syncer/follower_service.go
  mysqlcluster/syncer/headless_service.go
  mysqlcluster/syncer/leader_service.go
  mysqlcluster/syncer/metrics_service.go
  mysqlcluster/syncer/mysql_cm.go
  mysqlcluster/syncer/pdb.go
  mysqlcluster/syncer/role.go
  mysqlcluster/syncer/rolebinding.go
  mysqlcluster/syncer/secret.go
  mysqlcluster/syncer/serviceaccount.go
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/status.go
  mysqlcluster/syncer/xenon_cm.go
Labels: enhancement

#670 api,backup: add printcolumn for Success #668
  api/v1alpha1/backup_types.go
  backup/syncer/job.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
Labels: enhancement
