Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-07, with the labels that each got.

#561 job,controllers: clear history job must do in cluster, not in namespa…
  backup/backup.go
  backup/syncer/job.go
  controllers/backup_controller.go
Labels: bug

#567 fix(cluster): failed to update volume size.
  mysqlcluster/syncer/statefulset.go
  mysqlcluster/syncer/statefulset_test.go
Labels: bug

#569 fix(cluster): configmap abnormal update
  mysqlcluster/syncer/mysql_cm.go
Labels: bug

#568 dockerfile: Remove GOPROXY settings in dockerfile
  Dockerfile
  Dockerfile.sidecar
Labels: enhancement

#574 controllers,mysqlcluster: fix the backup Running bug#572
  controllers/backup_controller.go
  mysqlcluster/syncer/statefulset.go
Labels: bug

#578 release v2.2.0
  charts/mysql-operator/Chart.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
Labels: minor

#582 doc: add backupschedule docs in zh
  docs/zh-cn/backup_cron.md
Labels: documentation

#596 *: Add inCluster related API and xenon checker
  build/xenon/Dockerfile
  cmd/staticcheck.conf
  cmd/xenon/main.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  utils/incluster.go
Labels: enhancement

#597 *: Prevent Leader from accidentally hanging up data inconsistency
  Dockerfile
  Dockerfile.sidecar
  build/mysql/Dockerfile
  build/xenon/Dockerfile
  cmd/xenon/main.go
  config/samples/mysql_v1alpha1_backup.yaml
  go.mod
  go.sum
  hack/xenon/Dockerfile
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  mysqlcluster/syncer/role.go
  sidecar/config.go
  sidecar/init.go
Labels: enhancement

#593 Doc: Add backup_cron in English #564
  README.md
  README_zh.md
  docs/en-us/backup_and_restoration_nfs.md
  docs/en-us/backup_and_restoration_s3.md
  docs/en-us/backup_cron.md
  docs/zh-cn/backup_and_restoration_nfs.md
  docs/zh-cn/backup_and_restoration_s3.md
  docs/zh-cn/backup_cron.md
  docs/zh-cn/mgt_mysqluser.md
Labels: documentation

#600 *: remove useless import and clear logic of xenonchecker.
  api/v1alpha1/mysqlcluster_types.go
  build/xenon/Dockerfile
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  cmd/xenon/main.go
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  go.mod
  go.sum
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
  sidecar/config.go
  utils/constants.go
Labels: duplicate, enhancement, format

#575 *: Support to configure grant option and SSL when creating users.
  api/v1alpha1/mysqluser_types.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlusers.yaml
  config/crd/bases/mysql.radondb.com_mysqlusers.yaml
  config/samples/mysql_v1alpha1_mysqluser.yaml
  controllers/mysqluser_controller.go
  internal/sql_runner.go
Labels: enhancement, require-doc

#603 mysqlcluster: remove error role policy rule
  mysqlcluster/syncer/role.go
Labels: bug

#585 internal: support changing passwords.
  internal/sql_runner.go
Labels: enhancement

#601 feat(user): Use super users to replace root user
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
  config/samples/mysql_v1alpha1_mysqluser.yaml
  config/samples/mysqluser_secret.yaml
Labels: enhancement

#613 ci: update the codecheck items and the build items.
  .github/workflows/build_xenon_image.yml
  .github/workflows/code_check.yml
  .github/workflows/publish_images.yml
Labels: enhancement, workflow

#617 config,controllers: fix the bug of fail to create role
  config/rbac/role.yaml
  controllers/mysqlcluster_controller.go
Labels: bug

#618 ci: add more assets in release
  .github/workflows/publish_charts.yml
  .github/workflows/publish_images.yml
  .github/workflows/publish_release.yml
  .github/workflows/release_drafter.yml
Labels: enhancement, workflow

#623 *: improve security
  controllers/mysqluser_controller.go
  internal/sql_runner.go
  mysqlcluster/container/auditlog.go
  mysqlcluster/container/backup.go
  mysqlcluster/container/container.go
  mysqlcluster/container/init_mysql.go
  mysqlcluster/container/init_sidecar.go
  mysqlcluster/container/metrics.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/container/slowlog.go
  mysqlcluster/container/xenon.go
  mysqlcluster/syncer/secret.go
  mysqlcluster/syncer/status.go
  sidecar/config.go
  sidecar/init.go
  sidecar/util.go
Labels: enhancement, Improvement
