Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2022-09, with the labels that each got.

#683 api: add webhook for nfs backup #667
  api/v1alpha1/mysqlcluster_webhook.go
Labels: bug

#679 *: add disk usage check in nfs backup #663
  Makefile
  backup/syncer/job.go
Labels: enhancement

#685 chart: remove v1.0
  charts/helm/Chart.yaml
  charts/helm/README.md
  charts/helm/dockerfiles/mysql/Dockerfile
  charts/helm/dockerfiles/mysql/README.md
  charts/helm/dockerfiles/mysql/my.cnf
  charts/helm/dockerfiles/mysql/mysql-entry.sh
  charts/helm/dockerfiles/xenon/Dockerfile
  charts/helm/dockerfiles/xenon/README.md
  charts/helm/dockerfiles/xenon/xenon-entry.sh
  charts/helm/templates/NOTES.txt
  charts/helm/templates/_helpers.tpl
  charts/helm/templates/configmap.yaml
  charts/helm/templates/rbac.yaml
  charts/helm/templates/secrets.yaml
  charts/helm/templates/service.yaml
  charts/helm/templates/serviceaccount.yaml
  charts/helm/templates/servicemonitor.yaml
  charts/helm/templates/statefulset.yaml
  charts/helm/values.yaml
  docs/en-us/mysql.md
  docs/en-us/xenon.md
  docs/zh-cn/mysql.md
  docs/zh-cn/xenon.md
Labels: cleanup, chart

#688 *: fix the bug status always empty till backup complete #687
  api/v1alpha1/backup_types.go
  backup/syncer/job.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_backups.yaml
  controllers/backup_controller.go
Labels: bug

#647 *: Support MySQL subversion
  Dockerfile
  Dockerfile.sidecar
  Makefile
  api/v1alpha1/mysqlcluster_types.go
  api/v1alpha1/mysqlcluster_webhook.go
  api/v1alpha1/webhook_suite_test.go
  build/mysql/Dockerfile
  build/xenon/Dockerfile
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
  config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
  docs/en-us/backup_and_restoration_s3.md
  docs/en-us/backup_cron.md
  docs/zh-cn/backup_and_restoration_s3.md
  mysqlcluster/container/init_mysql.go
  mysqlcluster/container/init_mysql_test.go
  mysqlcluster/container/init_sidecar_test.go
  mysqlcluster/container/mysql.go
  mysqlcluster/container/mysql_test.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/mysqlcluster_test.go
  mysqlcluster/syncer/mysql_cm.go
  test/e2e/framework/mysqlcluster.go
  utils/common.go
  utils/constants.go
Labels: enhancement

#656 *: support MySQL configuration template
  api/v1alpha1/mysqlcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  charts/mysql-operator/templates/mysql57_template.yaml
  charts/mysql-operator/templates/mysql80_template.yaml
  charts/mysql-operator/values.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  controllers/mysqlcluster_controller.go
  mysqlcluster/mysqlcluster.go
  mysqlcluster/syncer/mysql_cm.go
  mysqlcluster/syncer/objectSyncer.go
  mysqlcluster/syncer/statefulset.go
  sidecar/config.go
  sidecar/init.go
Labels: enhancement, Improvement, CRD, draft

#697 feat(e2e): add podchaos api and test cases
  test/e2e/chaos/podChaos.go
  test/e2e/e2e_test.go
  test/e2e/framework/chaos.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/framework.go
  test/e2e/framework/mysqlcluster.go
Labels: enhancement, e2e

#692 sidecar: remove xtrabackup copy back #691
  sidecar/config.go
  sidecar/init.go
  sidecar/util.go
Labels: bug

#584 *: Support running single node. #361
  api/v1alpha1/mysqlcluster_types.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  controllers/mysqlcluster_controller.go
  mysqlcluster/container/xenon.go
  mysqlcluster/container/xenon_test.go
Labels: enhancement

#537 mysqlcluster: when image set error, use replica 0 to rescure it #531
  mysqlcluster/syncer/statefulset.go
Labels: bug
