Repository radondb/radondb-mysql-kubernetes, pull requests merged in 2023-02, with the labels that each got.

#755 Update NOTES.txt
  charts/mysql-operator/templates/NOTES.txt
Labels: bug

#759 api: adjust the api structure
  PROJECT
  api/v1beta1/groupversion_info.go
  api/v1beta1/mysqlcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/crd/kustomization.yaml
  config/samples/mysql_v1beta1_mysqlcluster.yaml
  controllers/suite_test.go
Labels: enhancement

#762 V3: v1beta1 backup as storage version
  PROJECT
  api/v1alpha1/backup_conversion.go
  api/v1alpha1/backup_webhook.go
  api/v1alpha1/mysqlcluster_conversion.go
  api/v1alpha1/mysqlcluster_types.go
  api/v1beta1/backup_conversion.go
  api/v1beta1/backup_types.go
  api/v1beta1/mysqlcluster_conversion.go
  api/v1beta1/mysqlcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
  charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
  cmd/manager/main.go
  config/crd/bases/mysql.radondb.com_backups.yaml
  config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_backups.yaml
  config/crd/patches/webhook_in_backups.yaml
  config/samples/mysql_v1alpha1_mysqlcluster.yaml
  controllers/mysqlcluster_controller.go
  mysqlcluster/syncer/pdb.go
Labels: draft

#763 V3: init mysqlserver conversion, remove backup crd conversion
  PROJECT
  api/v1alpha1/backup_conversion.go
  api/v1alpha1/backup_webhook.go
  api/v1beta1/backup_conversion.go
  api/v1beta1/mysqlcluster_conversion.go
  cmd/manager/main.go
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_backups.yaml
  config/crd/patches/webhook_in_mysqlclusters.yaml
  config/manager/kustomization.yaml
  config/samples/mysql_v1beta1_backup.yaml
Labels: enhancement
